baseURL = "https://l0c0.org/"
languageCode = "en-us"
title = "L0C0 | Cybersecurity Research"

[[module.imports]]
path = "github.com/nunocoracao/blowfish/v3"

[params]
  description = "Independent Cybersecurity Research"
  defaultAppearance = "dark"
  autoSwitchAppearance = false

[params.homepage]
  layout = "background"
  showRecent = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
